title: "Android Development - Room Databases"
author: "Justin Kindrix"
description: "A comprehensive guide to Android Development using Kotlin, Jetpack Compose, Hilt, and Room."
baseurl: "/books/android-room-databases"
url: "https://jkindrix.dev/books/android-room-databases" # the base hostname & protocol for your site

remote_theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate

collections:
  chapters:
    output: true
    permalink: /books/android-room-databases/:collection/:name

nav:
  - title: "Home"
    url: /books/android-room-databases/
  - title: "Introduction"
    url: /books/android-room-databases/chapters/introduction/
  - title: "Getting Started"
    url: /books/android-room-databases/chapters/getting-started/
  - title: "Advanced Topics"
    url: /books/android-room-databases/chapters/advanced-topics/
  - title: "Appendix"
    url: /books/android-room-databases/chapters/appendix/

defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: "default"
      author: "Justin Kindrix"
