title: "Justin Kindrix's Site"
author: "Justin Kindrix"
description: "A collection of resources on various topics by Justin Kindrix, including books, tutorials, and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jkindrix.dev" # the base hostname & protocol for your site

remote_theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate

nav:
  - title: "Home"
    url: /
  - title: "Books"
    url: /books/
  - title: "Tutorials"
    url: /tutorials/
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Justin Kindrix"
